---
project_name: mockbob
archives:
  - id: main
    wrap_in_directory: true
    files:
      - README.md
builds:
  - main: ./cmd
    binary: mockbob
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goos:
      - darwin
      - linux
      - freebsd
      - openbsd
    ignore:
      - goos: freebsd
        goarch: arm
      - goos: openbsd
        goarch: arm
      - goos: freebsd
        goarch: arm64
      - goos: openbsd
        goarch: arm64
    env:
      - CGO_ENABLED=0
